[package]
name = "soundtoys"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic_float = "0.1"
cpal = "0.15"
dyn-clone = "1.0"
rand = { version = "0.8", features = ["small_rng"] }
thiserror = "1.0"
